GET http://localhost:4000/api/posts

###
POST http://localhost:4000/api/posts
Content-Type: application/json

{
    "id": 0,
    "name": "First Post"
}

###
POST http://localhost:4000/api/posts
Content-Type: application/json

{
    "id": 1,
    "name": "Second Post"
}

###
GET http://localhost:4000/api/posts/1



###


DELETE  http://localhost:4000/api/posts/



